name: build

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        run: |
          python -m pip install --upgrade pip twine wheel
          python -m pip install pytest
          python -m pip install -e .
          pytest ./test

      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user
      
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build
          --source
          --binary
          --out-dir dist/
          .

      - name: Publish a Python distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

          
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        run: |
          python -m pip install --upgrade pip twine wheel
          python -m pip install -e .
          pytest ./test

